# Phase 4.2 cluster broker #3 (tarball mode)
process.roles=broker,controller
node.id=3
controller.quorum.voters=1@localhost:9093,2@localhost:9193,3@localhost:9293

listeners=PLAINTEXT://:9292,CONTROLLER://:9293
advertised.listeners=PLAINTEXT://localhost:9292
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
inter.broker.listener.name=PLAINTEXT

num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600

log.dirs=/tmp/kafka-cluster-tarball/broker-3
num.partitions=1
num.recovery.threads.per.data.dir=1

# 集群默认值（topic 没显式覆盖时生效）
offsets.topic.replication.factor=3
transaction.state.log.replication.factor=3
transaction.state.log.min.isr=2
default.replication.factor=3
min.insync.replicas=2
auto.create.topics.enable=false

log.retention.hours=168
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000

group.initial.rebalance.delay.ms=0
