port 6379
dir /tmp/redis-sentinel/master
pidfile /tmp/redis-sentinel/master.pid
dbfilename dump.rdb
appendonly yes
appendfsync everysec
daemonize no
loglevel notice
logfile /tmp/redis-sentinel/master.log
# 副本可写不必，但允许复制后链式 replication 更稳
replica-read-only yes
