port 6381
dir /tmp/redis-sentinel/replica-2
pidfile /tmp/redis-sentinel/replica-2.pid
dbfilename dump.rdb
appendonly yes
appendfsync everysec
daemonize no
loglevel notice
logfile /tmp/redis-sentinel/replica-2.log
# 跟主：sentinel failover 后 sentinel 会改写这一行
replicaof 127.0.0.1 6379
replica-read-only yes
