port 26379
dir /tmp/redis-sentinel/sentinel-1
pidfile /tmp/redis-sentinel/sentinel-1.pid
daemonize no
loglevel notice
logfile /tmp/redis-sentinel/sentinel-1.log

# 监控的主：name=im-master，addr=127.0.0.1:6379，quorum=2（2 个 sentinel 同意才 failover）
sentinel monitor im-master 127.0.0.1 6379 2

# 主在 5 秒没响应判 down
sentinel down-after-milliseconds im-master 5000
# failover 时同时跟新主同步的 replica 数
sentinel parallel-syncs im-master 1
# failover 全程超时
sentinel failover-timeout im-master 30000
