# Phase 5 az1 单 broker（轻量演示用，RF=1）
process.roles=broker,controller
node.id=20
controller.quorum.voters=20@localhost:9593
listeners=PLAINTEXT://:9592,CONTROLLER://:9593
advertised.listeners=PLAINTEXT://localhost:9592
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
inter.broker.listener.name=PLAINTEXT

log.dirs=/tmp/mm2-tarball/az2-broker
num.partitions=1

offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
default.replication.factor=1
min.insync.replicas=1
auto.create.topics.enable=false

log.retention.hours=24
log.segment.bytes=536870912
group.initial.rebalance.delay.ms=0
